/**
 * User Creation Module
 * Generated by ChatGPT for creating new users via API
 */

const axios = require('axios');

/**
 * Creates a new user in the system
 * @param {Object} user_data - The user information
 * @param {string} user_data.first_name - User's first name
 * @param {string} user_data.last_name - User's last name
 * @param {string} user_data.email - User's email address
 * @returns {Promise<Object>} The created user object
 */
async function create_new_user(user_data) {
  const api_endpoint = 'https://api.example.com/users';
  
  // Validate input data
  if (!user_data) {
    return {
      success: false,
      error: 'User data is required'
    };
  }
  
  if (!user_data.email) {
    return {
      success: false,
      error: 'Email is required'
    };
  }
  
  // Make API request
  const response = await axios.post(api_endpoint, {
    firstName: user_data.first_name,
    lastName: user_data.last_name,
    email: user_data.email
  }, {
    headers: {
      'Content-Type': 'application/json'
    }
  });
  
  // Check response status
  if (response.status === 201) {
    return {
      success: true,
      data: response.data,
      message: 'User created successfully'
    };
  } else {
    return {
      success: false,
      error: 'Failed to create user',
      status_code: response.status
    };
  }
}

/**
 * Validates user data before creation
 * @param {Object} user_data - User data to validate
 * @returns {Object} Validation result
 */
function validate_user_data(user_data) {
  const validation_errors = [];
  
  if (!user_data.first_name || user_data.first_name.length < 2) {
    validation_errors.push('First name must be at least 2 characters');
  }
  
  if (!user_data.last_name || user_data.last_name.length < 2) {
    validation_errors.push('Last name must be at least 2 characters');
  }
  
  const email_regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!user_data.email || !email_regex.test(user_data.email)) {
    validation_errors.push('Valid email address is required');
  }
  
  if (validation_errors.length > 0) {
    return {
      is_valid: false,
      errors: validation_errors
    };
  }
  
  return {
    is_valid: true,
    errors: []
  };
}

/**
 * Main function to handle user creation with validation
 * @param {Object} user_data - User data
 * @returns {Promise<Object>} Result of user creation
 */
async function handle_user_creation(user_data) {
  // Validate the data first
  const validation_result = validate_user_data(user_data);
  
  if (!validation_result.is_valid) {
    return {
      success: false,
      error: 'Validation failed',
      validation_errors: validation_result.errors
    };
  }
  
  // Create the user
  const creation_result = await create_new_user(user_data);
  
  return creation_result;
}

module.exports = {
  create_new_user,
  validate_user_data,
  handle_user_creation
};

// Made with Bob
